# Generated by Django 4.2.6 on 2024-11-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='id',
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='username',
            field=models.CharField(default='default@example.com', max_length=150, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
